on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: TSAN Integration Test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: nightly
            build: ""
          - rust: nightly
            build: "--release"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rust-src
          toolchain: ${{ matrix.rust }}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: nightly
          args: ${{ matrix.build }} --features=short-potato --manifest-path bbqtest/Cargo.toml -Zbuild-std --target x86_64-unknown-linux-gnu -- --nocapture
        env:
          RUSTFLAGS: "-Z sanitizer=thread"
          RUST_TEST_THREADS: 1
          TSAN_OPTIONS: "suppressions=${{ github.workspace }}/tsan-blacklist.txt"
